const AddProductImage = () => {
    return (
        <svg
            className="image--addProduct"
            viewBox="0 0 2630.79 1695.32"
        >
            <g>
                <rect
                    className="cls-1B"
                    x="-5476.59"
                    y="-7525.2"
                    width="9809.85"
                    height="9381.84"
                />
            </g>
            <g>
                <g>
                    <rect
                        className="cls-2B"
                        x="294.85"
                        y="432.87"
                        width="454.04"
                        height="563.12"
                        rx="36.27"
                    />
                    <rect
                        className="cls-3B"
                        x="562.9"
                        y="432.87"
                        width="44.13"
                        height="563.64"
                    />
                    <rect
                        className="cls-4B"
                        x="1914.53"
                        y="815.17"
                        width="454.04"
                        height="443.93"
                        rx="36.27"
                        transform="translate(4283.1 2074.28) rotate(-180)"
                    />
                    <rect
                        className="cls-3B"
                        x="2056.4"
                        y="815.17"
                        width="44.13"
                        height="444.34"
                        transform="translate(4156.92 2074.69) rotate(-180)"
                    />
                </g>
                <g>
                    <g>
                        <rect
                            className="cls-5Btransparent"
                            x="605.61"
                            y="321.86"
                            width="1449.03"
                            height="1032.06"
                            rx="37.12"
                        />
                        <line
                            className="cls-5B"
                            x1="605.61"
                            y1="407.74"
                            x2="2054.64"
                            y2="407.74"
                        />
                        <rect
                            className="cls-6B"
                            x="803.47"
                            y="357.23"
                            width="28.32"
                            height="28.32"
                            rx="10.49"
                        />
                        <rect
                            className="cls-6B"
                            x="755.16"
                            y="357.23"
                            width="28.32"
                            height="28.32"
                            rx="10.49"
                        />
                        <rect
                            className="cls-6B"
                            x="706.85"
                            y="357.23"
                            width="28.32"
                            height="28.32"
                            rx="10.49"
                        />
                        <rect
                            className="cls-4B"
                            x="797.63"
                            y="352.03"
                            width="28.32"
                            height="28.32"
                            rx="10.49"
                        />
                        <rect
                            className="cls-2B"
                            x="749.32"
                            y="352.03"
                            width="28.32"
                            height="28.32"
                            rx="10.49"
                        />
                        <rect
                            className="cls-7B"
                            x="701"
                            y="352.03"
                            width="28.32"
                            height="28.32"
                            rx="10.49"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default AddProductImage;
